language: minimal

os: linux

services:
  - docker

env:
  - container_image="intersystemsdc/iris-community:latest"
    instance="iris"
    package="pkg.yourcompany.math"
    build_flags="-verbose"
    >
    test_flags="-verbose
    -DUnitTest.ManagerClass=TestCoverage.Manager
    -DUnitTest.JUnitOutput=/source/junit.xml
    -DUnitTest.FailuresAreFatal=1
    -DUnitTest.UserParam.CoverageReportClass=TestCoverage.Report.Cobertura.ReportGenerator
    -DUnitTest.UserParam.CoverageReportFile=/source/coverage.xml"

install:
  # Run InterSystems IRIS instance
  - docker pull $container_image
  - docker run -d -h $instance --name $instance -v $TRAVIS_BUILD_DIR:/source --init $container_image
  - echo halt > wait
  # Wait for instance to be ready
  - until docker exec --interactive $instance iris session $instance < wait; do sleep 1; done
  # Install TestCoverage
  - echo "zpm \"install testcoverage\":1:1" > install-testcoverage
  - docker exec --interactive $instance iris session $instance -B < install-testcoverage
  # Workaround for permissions issues in TestCoverage (creating directory for source export)
  - chmod 777 $TRAVIS_BUILD_DIR

script:
  # Run build
  - echo "zpm \"load /source $build_flags\":1:1" > build
  # Run tests
  - echo "zpm \"$package test -only $test_flags\":1:1" > test
  - docker exec --interactive $instance iris session $instance -B < build && docker exec --interactive $instance iris session $instance -B < test

after_success:
  # Publish to codecov
  - bash <(curl -s https://codecov.io/bash)
