ROUTINE pkg.yourcompany.math [Type=INC]

#define LeastCommonMultiple		##class(pkg.yourcompany.math.Math).LeastCommonMultiple
#define LCM		##class(pkg.yourcompany.math.Math).LCM

#define GreatestCommonDivisor		##class(pkg.yourcompany.math.Math).GreatestCommonDivisor
#define GCD		##class(pkg.yourcompany.math.Math).GCD

#define Max		##class(pkg.yourcompany.math.Math).Max

#define Min		##class(pkg.yourcompany.math.Math).Min

#define Factorial		##class(pkg.yourcompany.math.Math).Factorial

#define Ceiling ##class(pkg.yourcompany.math.Math).Ceiling

#define Floor ##class(pkg.yourcompany.math.Math).Floor